export type PaymentStatus =
  | 'pending'
  | 'approved'
  | 'rejected'
  | 'pending-approval';

export interface Payment {
  id: number;
  date: string;
  status: PaymentStatus;
  description: string;
  supplier: string;
  currentAmount: number;
  totalAmount: number;
  currentNumberOfPayments: number;
  totalNumberOfPayments: number;
  pdfUrl: string;
}

export const PAYMENTS: Payment[] = [
  {
    id: 1,
    date: '2025-04-10',
    status: 'pending',
    description: 'יום צילום',
    supplier: 'ספק א',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 2,
    date: '2025-04-05',
    status: 'approved',
    description: 'יום צילום',
    supplier: 'ספק ב',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 3,
    currentNumberOfPayments: 2,
    date: '2025-04-05',
    status: 'rejected',
    description: 'יום צילום',
    supplier: 'ספק ג',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    pdfUrl: 'Keshet - Home Assignment - Payment.pdf',
  },
  {
    id: 4,
    date: '2025-04-05',
    status: 'pending',
    description: 'יום צילום',
    supplier: 'ספק ד',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 5,
    date: '2025-04-05',
    status: 'approved',
    description: 'יום צילום',
    supplier: 'ספק ה',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 6,
    date: '2025-04-05',
    status: 'rejected',
    description: 'יום צילום',
    supplier: 'ספק ו',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 7,
    date: '2025-04-05',
    status: 'pending',
    description: 'יום צילום',
    supplier: 'ספק א',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 8,
    date: '2025-04-05',
    status: 'approved',
    description: 'יום צילום',
    supplier: 'ספק ב',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 9,
    date: '2025-04-05',
    status: 'rejected',
    description: 'יום צילום',
    supplier: 'ספק ג',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 10,
    date: '2025-04-05',
    status: 'pending',
    description: 'יום צילום',
    supplier: 'ספק ד',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 11,
    date: '2025-04-05',
    status: 'approved',
    description: 'יום צילום',
    supplier: 'ספק ה',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 12,
    date: '2025-04-05',
    status: 'rejected',
    description: 'יום צילום',
    supplier: 'ספק ו',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 13,
    date: '2025-04-05',
    status: 'pending',
    description: 'יום צילום',
    supplier: 'ספק א',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 14,
    date: '2025-04-05',
    status: 'approved',
    description: 'יום צילום',
    supplier: 'ספק ב',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
  {
    id: 15,
    date: '2025-04-05',
    status: 'pending-approval',
    description: 'יום צילום',
    supplier: 'ספק ג',
    currentAmount: 500,
    totalAmount: 1500,
    totalNumberOfPayments: 3,
    currentNumberOfPayments: 2,
    pdfUrl: 'sample.pdf',
  },
];
